#!/bin/sh
echo 'HHHHHHHHHHHHHHHH@H@HH@H@@H@@HMM9=<~____~~~~........``.``````      ` __?TWM@@@@@@@@@@@@@@@@@@@@@@@@@@@H@@@H@H@H@@@H@HH@@H@@H@@@H@H@H@HH@HHH@HHH@HHHHHHH
HHHHHHHHHHH@HH@HH@@@HH@@H@MBY<-(<;;:<<~~~~......`.`.`````````          ` _7HH@@@@H@@@@@H@@@H@H@H@HH@H@HH@@H@H@H@H@H@HH@@H@HH@H@@@H@@@H@H@HH@H@HH@@HHHH
HHHH@HHHHHHHH@HH@HHH@HHMM9<(+=??>;:~~~~~~.......````.```````` `  `  `    `` ?W@H@HH@H@@H@@H@H@@@H@@H@@H@HH@H@HH@@@H@@H@HH@@@H@@H@@H@H@@HH@HH@H@H@H@@HH
@@H@H@HHHH@H@@@@@@@@@@M9<(zrtz<;;:::~~~~.......`.``````````` `  `         ` ` 7H@@H@@H@@@H@@@@H@@@@@H@@@@@H@@@@H@H@@H@@H@H@@@@H@@H@H@@H@H@H@HHH@H@H@H@
H@@HH@H@H@H@HH@@H@@H@#3(zzurtz<>;;:~~~........``.`.````````` ``      ` ` ` ` ` ?H@H@@@HH@@H@H@@H@H@@@HHH@H@HH@@H@@HH@HH@HHH@HH@HH@@@H@@H@H@H@@HH@H@HHH
HH@H@H@H@H@@@H@@@HM@#>(duXzrtzz><~~~~.~....._---((----... ``` `` ` `   `  `   ` dM@HH@HH@H@@H@@H@H@@@@@@MMMMMMMMMMMM@H@@@@@H@@@@@@@H@H@@H@H@H@@H@H@@H@
H@HHH@H@H@H@@@H@@H@@D.(wzzvttlz<~~~~..--(+zzwwwwwwwwwOOzzz+--.``` ` `   ` ` `   JMMHHH@H@HM@H@H@@MHYY=<~_......`____~<?7TYWMMM@@@@H@H@HH@HH@HHH@H@HH@H
HH@HH@@@H@@HH@HHH@MMK__jrvrttlz;:~~_(+zwwXyXyVffVVVVVVyyXXwwOz+-.`````     ` ` -d###HMHHHMMY977<__....................`.``.` _??7YWMM@@H@@HH@@H@HH@HH@
@HH@@HH@@@@@@H@@HH@HM2._1Ottll<;<(+zwwXyyyfpfpffpppppffVVyyZXwvOz<.`` ``   `  (dMN##MMBY>~_ ..~.~.............~~...`..``.``````````` ~?7THMM@H@@@H@HHH
H@H@@H@HH@HH@@@@HHHHHMm- _<1==<;;+zrzZyyyVffpfppffffffffVyyyZZzvtz< `   `` .(jdMMM9=!.-.__~~~(<<_~~.............``.``````.```.`````......` _?TWM@HHMHH
@H@H@@H@@@@@H@@H@@@@@@@Hm..  _<<<<1twXZyyyfpfpfpfpfffffVVyyyZXzrOv! ``` .-(uXH9>~-._~~_~~~~.~~<:<_........```_~<_(((--.. ```.```.````..  `` ``` ?TWM@@
H@HHH@@H@H@@@HH@HH@HHHHH@@Ha+--. `.`_??7TTUUUWWffffffVyyXXU0VOC<<~...-(+uXY^_..~~::;;::~~~.~..__```.(u&---  ...._~~~??zOOw&+-..````.```````````` ``_?T
H@@@@H@@HHHHHH@@HHHH@@@@@@H@@MHkmw&+-----__.-.__~<<<<!~_.__--(((J+&gQWY=~..__::~~:~<<<_~~~...```..._?zUUWHHm+--~~~~~__:~~<+1OXXX&-. `````````` ```````
@H@H@H@@H@@HHHHHHH@@HHHHH@@HH@@@@HHHHWWWkkkkmAA&&&&&&&eOAmkXQWWHMMB=!_-__~:~:::~~~~~~~...._(+&++++&+-JzyV9WHbWWk&-_~:<;;;<+(_~<?zVUI+-.```````` ``` `
@@H@H@H@@H@@@HHHH@@H@H@@@H@HH@HH@H@HHMMNHmmmmmqqqmmgggHHHHMMMMM9=_.__::(++<:~~~~~~.......(jwXfkXWWXOOwXzwtrwOwUyXZXwx+;<<<<<1?++<:<<<+zz+-.```````````
@@@H@@HH@HHHHHH@HH@HH@@H@@H@H@@H@@HHHHH##MNNHH@@@@HH@MHMMMMMY!.__~:::::(+?<<~~~.........-_1wXWWWWXXzOwttOllOvOwzZUXXUuww+-_._~:<<:__(:~~<?11+..```````
@@@@@H@@HH@@H@@@MM@@H@@H@@H@@@@@@@@HHHHH######NNNNNNNMMMB=~.___::::::~~~~~~~............_~(+1zOZXUUZvOOzwwzwz+11zzzzzOwXUXOz+-(++_::<<;><(_~~_`_-... `
@@HH@@H@H@@@@@H@HH@HH@@@@@@@@@@@@@@@H@HHHHHHH#H###NNMB=_-___(::::::~~~~~~~.._+++--_...-~~~~~~:~<?zOOz++XZuXZwOz11?ztz+1OOOtOwrttOz<:::<<(<;;__._>>><~
@H@H@@@@@@HH@H@H@@@HH@@@@H@@@@@@@@@H@@@HHHHHHHHHHM#=`.__::::::::::~~~~~....(+Olz?1+?zOOz+((__~~_~~~<<1?zXXZzOOtOOOz=llOz<?OZXzrwzUUwzzzzlz<~~..~_<;~_
@@@@HH@H@H@@H@@@@@@@@H@@HH@@@@@@@@@HH@@H@@@@HHHHY~.-__:<<:::::::~~~......._jwOOO=zllOuwrvO=IttOz--_._~(?zwvvrOlOlllltOlttz<<?OXXuvOOtlz<<<~..~~._(zz+-
@@@H@@H@@H@HH@@HH@H@@@H@@@@@@@@@@@@@@@H@@H@HM9^.-__::+?==<::~~~~~_...._.``_(OOvwO=zrvwXVI1XOtrtl11zI++_~~~<OXZwwvrOzwwuzrOOz<_<zwrtOuwAx-~~~._._-Juuww
@HH@HH@H@@HHH@H@@@@@@@@@@@@@g@@@@@@gH@@@@HHY~.-(:::::;<><<~~~~_.~_..__(+++++z+1wAwwwz?zOzOOOrtOz<;>+<<11+-~_<1wuZZyXXuuuuvwzrO<_<<<1zwuvw<~.-___jzzuzz
@H@@H@H@H@H@@@M@HMH@@@M@H@g@@gHqg@g@HH@M9=.-(jwwO<;;;:::~~~~....(z&+(>1O1?<<;?OXOzzOXwzzOz1zlltrwOzzzzzzrto-:<<1wyZXyZuvrwzwrrOz+(:::<1zO<<~~~(jrrvrwO
H@@@@@@H@@HHHMgHHMg@@@@@Mggg@@@@g@@@@@B^._(<+zZXZI;:::~~~......(zOI+Oz<1<<<::(1zVUUOwzXXXwzOOOvuuXwwXzXXwOOOO+(~<wXuZXXZZXXOlwXwOz<:(<~;;>;::+zlrOOz<<
@@HMMHH@HH@@@HH@H@@Hg@HMH@H@@@@@@@gMM=_-(<><?>+1C<~~~~~......~~jSzOl===+<++++(+zvUOzwfWwwXWXwwwXXuZZZZuzzwzzOXwz<<?OXwwvzvwyXXWyuwzzz<-<+??++=1<<<<~__
@@H@@H@@@H@@@@Hg@g@M@@@HMH@@@@H@g@H9~.(;:;>?>;;:::~~~.......`.__<1zzOOO?zz==<<<<;:<+wZWXuZXzZXXwZXXUXwzOwzOzzOOlz+++=OXWXWWpWUUUXrl<<~_(z=z??>:~~~..`.
@@M@@@@@@@@@H@mH@@@@g@@@H@@@@@@@gH= _(;;;>>>>;:~_~_..._....~__-__~?<zOwOzz><:::(<(zwzXZZXwuXZZuXWWXzrrI+zrrtOtlttrXwOz1OwUUzzOIztOz<~(+ll=ll=<<:...```
@gHH@@@@H@H@MHHMgH@HH@@@@@@g@HHHH> _<;;>>>>;;<:~<_~~~~~(<<<<<~<<11Oz+(<<1IOwyzzzzwwZX0XuuWWWXuvtOOUXwtOO=zwZOtOzlOXykwz><1OXvtzwXwzzzOOllllzz<<_...```
H@@HH@@H@H@@MM@@mHM@g@@HH@HggHH#!.(;;;+??<:~~__+z<:~__~_(<~_~~_++zzwOzz1+<+<1OXWppWXVOXXuXWWUOtlltOXWkwwOzttOtllllwXyuwz?>?zOlwzvvrtOz<<<<<<~_....``.`
M@@@H@@@@HMHH@@@@MH@@gHHHggH@@#!.(>>>?>?;<~~_((+><~~~~_(<<~____><?<ztzOOvrz++<<?OwWWXwOOwuzXI<+1+1+1wWWSXZtlzzwOXXZZXXXOz==zz1XuvrtOz<<~_......```````
HMM@@@@@@@gHHqH@@HH@@HMHggH@@M>`_+>???>;:~~.<<<<<_~~___<<_~.___~~ _<<1z1C+I=OO+_~<1wXrOltOzOz??>>+>1OrXWyz<<zz1Ollz<jWyktOz??zvvrOz<<<~...````````````
@@g@H@MM@@HgggH@@@@@@@@@@@MMH@  (????>;::_ _~~~~::_;_-_<1z<__~~~~_~(<+=++(1=<+1Oz_~(1OOttz?????1?zzzzwvZWI<~_:<1zv<jdZZZuzwwvrrrtI<:~~....````````.```
@@m@@@@MH@@@m@@@M@@M@@@@g@@@@%`.(????>::~_ _~~~~~_((<__(+Oz<_:~~~~((+>+zI=z;<<+=z1z-(+ztOz(;??=+1=lzrvOwXXz_(+zzywXXZZZuuzzwwrOv1<<_....``.`.```.``.``
@@H@@M@HHMggH@@@@@@gH@@HHg@@M\`-<???>;::~_._<~(<:++=Z6CCv<?+<<+(__<11>+>z<<_(+<<(+=z1<<<<<(zz+wwzzlzvwwzrrOz1lwXZZXZZuuzvrrtz1<<~_.....``.```.`````.`
H@@@@@HHHH@gH@@@@@@g@g@gH@g@M}`-(1+?>><~~....~~~~<?<<<~<<:+z=z<<:<<_:;<::<<<_1+;<<1<<1><_<<+?zruwZvwwwuXZ=lzzlzZZwuzzzzvrrOz<<<~~....```.`````.`..`..(
@@@@MHH@Hg@HM@@@@@g@gHMgH@H@@[  (zOOz<:~~...-_~_~__~.~(+<+1=z+::::~_<+_~~:_+>1+<<?1><(+1(_~<1ztwUzuuXXX0tO===ll=zwzzzvrOO1<<<~_.....````````... ``.(dM
H@Hmg@@HmH@@@@@@@gg@@@Mg@@@H@L ._<+11<_~~..``__.._~~~~_<++<1111+<:_~(<<:_~:<<1z<;;<;;;>wkz+<+?=1vzrOwzOlll===?zzwzvzrrtz<<<:~~.....``.````.` .``.(qMMM
H@@HHgHqmkH@H@@@g@gg@@gH@@gH@N. _(;>>::~~...`.````` `_~_(?OX++OO?<<(:<~:~:~~<~<+<<<<>??zWWXkwzz+<+1OOOz1zttllzOzzvrrtl=<<:~~~....`````.``.````.(gMMMMM
HM@HgH@@HqHkHHg@HgMHMg@@@Hg@@@[` _(>>;::~~...`.``.````...~_<<1Ozz+??+<_(+<_:~:~_;+1zz+1wZXWVWWWks+;<+?<;juzvzvvvvvrrOz<<:~~.....``.````.``. .(gMMMMMMN
Mg@@gMg@HHHHHg@HgHHHHgH@HH@@@MH-` _:;;;:~~....`.```.```....~~~(?1z++ll1>><<:<;<(&zOOzozwWVyVVyyfXWky<<~~jzvvvvvvvvrlz<:~~.....`.``.`.``.` .(gMMMMMMNMM
gM@@HH@@@@MggH@g@HHHg@@MH@@@gH@N-` _~;;::~~....``.````````..._~~_<1zwwzzzI><<?+zWUX0VtOtwyyyyyZZXXXC_((jrrzzzvzvrrlz<<~~.....`.`.```.`..(+NMMMMMMNMMMM
@HggHHH@g@gqHMH@gHHgH@@@g@@@H@@HH,``__:;;:~~...`````.```````...__~<~~?OVO<;<lzlwIzOOOrtOzdZyZZZuuuXOrOtlOrvzvzzvrOz<<~~.....``.``.``..JgMMMNMMNMMMNMNN
HH@gggHg@gHW@@@gggM@g@H@g@@gMHH@gHo  _~:;><~~.....`.```.``````.``-_<~~_<<<;+rvOOz1zltOlz<dZZZZZuuvvrOl==zOOOOOO1<<<~_.....`.....`..(jNMMMNMMMNMMMMMMNN
@@@mH@@@HHk@Mg@gHMHg@g@g@@HgH@@Mg@Hm, `_~<::~~.....`.`````.````.`.`.__~~::<(11<<+zllzlz+uXZZZuuuzrrtv?<<<<<<<<<<:~~~.....`.`.`` -(gMMMMMMMNMMMNMNNMNMN
MgHHgHH@mqHMHH@g@HH@@HHH@@@MH@@@@HggHm.  _~:~~~_....`..``.``.`````````.__~~<<<~(1l==z?zwZZSZZuuurrrOz<<~~~~..~..........`.``.-(gMMMMMMMMNMMMMNMMNNNNNN
HMHHHmHHHMMHMMHggHHH@HHM@HMg@@Hg@gggMMHe.  __~~~~~.-...```````.`````````...._~~:<<<<1wuzzzzuuzzvOOI<<<~~.............````.(JgMMMMMMMNMNMMNMMMNMNNMNNNN
g@@@@@@@@HH@@HHqH@H@H@MHH@@@Hm@ggg@H@@ggHm.`` __~~~~.....`.``.``.``.``````...._~__..(OzzzzzzwOOz1<<<~~...........```` .(igMMMMMMMMMMMMMMMMNNMMNNNNNNNN
H@@@@HHHHgg@@HH@HgHg@gg@@Hg@Hgg@gHHg@Hm@HHMm..   ~~~~~.......`..``.`````````.. ..._(jrrrvvrOI<<<~~_.~......`.` `` .(JgMMMMMMMMMMMMMMNMNMMNNMNNNNNNNNN#
HqHHHHgHHmH@H@g@ggHH@gH@ggggggmgmgmHH@@@@@@@@Ha..  ` _...........```.`````````.._(+tttrrrOzz<<_~.~.._~___.``..-(ugNMMMMMMMMMMMMMMNMMMNMNNNNNNNNNNN####
g@ggg@HHMgHHHMggggHHmH@@H@ggHHgg@@@@MMH@@M@@@@@@Hm.. ``.`...........`...`.`````._<<?+<<<<<~_~..._..```...(J+gNMMMMMMMMMMMMMMMMNMMNMNMNNMNNNNNN##N#M##H
gggg@HHHH@HgHHgHqHgNHHgmmg@@@M@gg@@Hg@@@@@MHH@@MH@g@HmJ-.```````..`...`..`...........~.__`  ```` ..((jggNMMMMMMMMMMMMMMMNMMMNMMNNMNNNNNNNNNNN####MHM##'
